### ISSUE TITLE
Improve tables

### ISSUE THREAD

**Issue by ivanadob** [histories-in-transition/hit-astro#1]
What to do: 
1. set the sorting function
2. drop down suggestions
3. pagination (not necessary for now, but maybe in the future?)

Consider using a headless table (e.g. TanStack) that provides the calculation but does not control the style and markup - overkill for now. 

- [x] #19
- [x] #20
- [x] #21
- [x] #23
- [x] #32

**Comment by csae8092** [comment]
Please use [tabulator.js ](https://tabulator.info/) as it includes all mentioned features (and many many more) out of the box
