### ISSUE TITLE
fix broken build workflow

### ISSUE THREAD

**Issue by csae8092** [histories-in-transition/hit-astro#4]
as of commit https://github.com/histories-in-transition/hit-astro/commit/e61568fc88a25734c663b2e737c4ffd8fb93d47c the build workflow fails

**Comment by ivanadob** [comment]
Problem with data entries: how to get title of work in the hands table. Each hand can have several hand_roles, originally with only ONE ms_item with one title_work -> [{title}] to it, but this did not hold.
