### ISSUE TITLE
add date and place column in table msItems

### ISSUE THREAD

**Issue by ivanadob** [histories-in-transition/hit-astro#43]
In msitems table  the user should be able to search for a specific work and get the instances (msItem) with date and place of the respecitive hands involved in it (from hands.json). - Read two json files in tabulator - > need to preprocess the

**Comment by csae8092** [comment]
* in case of several hands with different dates "Datum der Bearbeitung" currently looks e.g. like 821-975-999, split the values, order it, and just keep the lowest and highest
* maybe add default not-before and not-after values (e.g. 700 and 1300) to fill missing values
